grafana:
  enabled: true
  adminPassword: "Healthcare2026!"
  service:
    type: ClusterIP

prometheus:
  prometheusSpec:
    retention: 30d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

alertmanager:
  enabled: true
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname', 'namespace']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'null'
    receivers:
      - name: 'null'

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true