grafana:
  enabled: true
  adminPassword: "Healthcare2026!"
  service:
    type: ClusterIP

prometheus:
  enabled: true
  prometheusSpec:
    retention: 24h
    resources:
      requests:
        memory: 400Mi
        cpu: 200m
      limits:
        memory: 600Mi
        cpu: 500m
    storageSpec: {}

alertmanager:
  enabled: true
  alertmanagerSpec:
    resources:
      requests:
        memory: 100Mi
        cpu: 50m
      limits:
        memory: 200Mi
        cpu: 100m

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true

prometheusOperator:
  enabled: true